openapi: "3.0.0"
info:
  title: Paju Sales order API
  description: API Test
  version: "1.0.0"
servers:
  - url: https://localhost
paths:
  /salesorders:
    get:
      description: 'Returns all Sales Orders'
      responses:
          '200':
            description: A list of sales orders
            content:
              application/json:
                schema:
                  $ref: '#components/schemas/ListOfSalesOrders'

components:
  schemas:
    ListOfSalesOrders:
      type: object
      required:
        - id
        - customer_id
      properties:
        id:
          type: string
        customer_id:
          type: string
        products:
          type: array
          items:
            $ref: '#/components/schemas/Product'
    Product:
      type: object
      required:
        - id
        - name
        - unit_price
      properties:
        id:
          type: string
        name:
          type: string
        quantity:
          type: number
        unit_price:
          $ref: '#/components/schemas/Price'
    Price:
      type: object
      required:
        - price
        - currency
        - vat
      properties:
        price:
          type: number
        currency:
          type: string
          enum:
            - eur
        vat:
          type: string
          enum:
            - vat0
            - vat14
            - vat24
